Update package.json to support typescript node16
Typescript 4.7 with moduleResolution "node16" now looks for a "types" field
inside the "exports" section of the package.json and ignores the top-level
"types" field.  Thus with typescript 4.7 and moduleResolution "node16",
you get an error

error TS7016: Could not find a declaration file for module 'jdenticon'.

See
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing